apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: evo-todo-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: <your.domain.example>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: evo-todo-service
            port:
              number: 80
  tls: []
