apiVersion: v1
kind: Service
metadata:
  name: evo-todo-service
  labels:
    app: evo-todo-backend
spec:
  selector:
    app: evo-todo-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
